export const BANK_LIST = [
  { value: '970425', label: 'Ngân hàng TMCP An Bình (ABB)', img: 'https://vietqr.co/storage/banks/abb.png' },
  { value: '970416', label: 'Ngân hàng TMCP Á Châu (ACB)', img: 'https://vietqr.co/storage/banks/acb.png' },
  { value: '970409', label: 'Ngân hàng TMCP Bắc Á (BAB)', img: 'https://vietqr.co/storage/banks/bab.png' },
  { value: '970418', label: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)', img: 'https://vietqr.co/storage/banks/bidv.png' },
  { value: '970438', label: 'Ngân hàng TMCP Bảo Việt (BVB)', img: 'https://vietqr.co/storage/banks/bvb.png' },
  { value: '546034', label: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank (CAKE)', img: 'https://vietqr.co/storage/banks/cake.png' },
  { value: '970444', label: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam (CBB)', img: 'https://vietqr.co/storage/banks/cbb.png' },
  { value: '422589', label: 'Ngân hàng TNHH MTV CIMB Việt Nam (CIMB)', img: 'https://vietqr.co/storage/banks/cimb.png' },
  { value: '533948', label: 'Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội (CITIBANK)', img: 'https://vietqr.co/storage/banks/citibank.png' },
  { value: '970446', label: 'Ngân hàng Hợp tác xã Việt Nam (COOPBANK)', img: 'https://vietqr.co/storage/banks/coopbank.png' },
  { value: '796500', label: 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh (DBS)', img: 'https://vietqr.co/storage/banks/dbs.png' },
  { value: '970406', label: 'Ngân hàng TMCP Đông Á (DOB)', img: 'https://vietqr.co/storage/banks/dob.png' },
  { value: '970431', label: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam (EIB)', img: 'https://vietqr.co/storage/banks/eib.png' },
  { value: '970408', label: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu (GPB)', img: 'https://vietqr.co/storage/banks/gpb.png' },
  { value: '970437', label: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh (HDB)', img: 'https://vietqr.co/storage/banks/hdb.png' },
  { value: '970442', label: 'Ngân hàng TNHH MTV Hong Leong Việt Nam (HLBVN)', img: 'https://vietqr.co/storage/banks/hlbvn.png' },
  { value: '458761', label: 'Ngân hàng TNHH MTV HSBC (Việt Nam) (HSBC)', img: 'https://vietqr.co/storage/banks/hsbc.png' },
  { value: '970456', label: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh (IBK - HCM)', img: 'https://vietqr.co/storage/banks/ibk.png' },
  { value: '970455', label: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội (IBK - HN)', img: 'https://vietqr.co/storage/banks/ibk.png' },
  { value: '970415', label: 'Ngân hàng TMCP Công thương Việt Nam (ICB)', img: 'https://vietqr.co/storage/banks/icb.png' },
  { value: '970434', label: 'Ngân hàng TNHH Indovina (IVB)', img: 'https://vietqr.co/storage/banks/ivb.png' },
  { value: '970463', label: 'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh (KBHCM)', img: 'https://vietqr.co/storage/banks/kb.png' },
  { value: '970462', label: 'Ngân hàng Kookmin - Chi nhánh Hà Nội (KBHN)', img: 'https://vietqr.co/storage/banks/kb.png' },
  { value: '668888', label: 'Ngân hàng Đại chúng TNHH Kasikornbank (KBank)', img: 'https://vietqr.co/storage/banks/kbank.png' },
  { value: '970466', label: 'Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh (KEBHANAHCM)', img: 'https://vietqr.co/storage/banks/kebhana.png' },
  { value: '970467', label: 'Ngân hàng KEB Hana – Chi nhánh Hà Nội (KEBHANAHN)', img: 'https://vietqr.co/storage/banks/kebhana.png' },
  { value: '970452', label: 'Ngân hàng TMCP Kiên Long (KLB)', img: 'https://vietqr.co/storage/banks/klb.png' },
  { value: '970449', label: 'Ngân hàng TMCP Bưu điện Liên Việt (LPBANK)', img: 'https://vietqr.co/storage/banks/lpbank.png' },
  { value: '970422', label: 'Ngân hàng TMCP Quân đội (MB)', img: 'https://vietqr.co/storage/banks/mb.png' },
  { value: '970426', label: 'Ngân hàng TMCP Hàng Hải (MSB)', img: 'https://vietqr.co/storage/banks/msb.png' },
  { value: '970428', label: 'Ngân hàng TMCP Nam Á (NAB)', img: 'https://vietqr.co/storage/banks/nab.png' },
  { value: '970419', label: 'Ngân hàng TMCP Quốc Dân (NCB)', img: 'https://vietqr.co/storage/banks/ncb.png' },
  { value: '801011', label: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội (NHB HN)', img: 'https://vietqr.co/storage/banks/nhb.png' },
  { value: '970448', label: 'Ngân hàng TMCP Phương Đông (OCB)', img: 'https://vietqr.co/storage/banks/ocb.png' },
  { value: '970414', label: 'Ngân hàng Thương mại TNHH MTV Đại Dương (Oceanbank)', img: 'https://vietqr.co/storage/banks/oceanbank.png' },
  { value: '970439', label: 'Ngân hàng TNHH MTV Public Việt Nam (PBVN)', img: 'https://vietqr.co/storage/banks/pbvn.png' },
  { value: '970430', label: 'Ngân hàng TMCP Xăng dầu Petrolimex (PGB)', img: 'https://vietqr.co/storage/banks/pgb.png' },
  { value: '970412', label: 'Ngân hàng TMCP Đại Chúng Việt Nam (PVCB)', img: 'https://vietqr.co/storage/banks/pvcb.png' },
  { value: '970429', label: 'Ngân hàng TMCP Sài Gòn (SCB)', img: 'https://vietqr.co/storage/banks/scb.png' },
  { value: '970410', label: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam (SCVN)', img: 'https://vietqr.co/storage/banks/scvn.png' },
  { value: '970440', label: 'Ngân hàng TMCP Đông Nam Á (SEAB)', img: 'https://vietqr.co/storage/banks/seab.png' },
  { value: '970400', label: 'Ngân hàng TMCP Sài Gòn Công Thương (SGICB)', img: 'https://vietqr.co/storage/banks/sgicb.png' },
  { value: '970443', label: 'Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)', img: 'https://vietqr.co/storage/banks/shb.png' },
  { value: '970424', label: 'Ngân hàng TNHH MTV Shinhan Việt Nam (SHBVN)', img: 'https://vietqr.co/storage/banks/shbvn.png' },
  { value: '970403', label: 'Ngân hàng TMCP Sài Gòn Thương Tín (STB)', img: 'https://vietqr.co/storage/banks/stb.png' },
  { value: '970407', label: 'Ngân hàng TMCP Kỹ thương Việt Nam (TCB)', img: 'https://vietqr.co/storage/banks/tcb.png' },
  { value: '963388', label: 'Ngân hàng số Timo by Ban Viet Bank (TIMO)', img: 'https://vietqr.co/storage/banks/timo.png' },
  { value: '970423', label: 'Ngân hàng TMCP Tiên Phong (TPB)', img: 'https://vietqr.co/storage/banks/tpb.png' },
  { value: '970458', label: 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh (UOB)', img: 'https://vietqr.co/storage/banks/uob.png' },
  { value: '546035', label: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank (Ubank)', img: 'https://vietqr.co/storage/banks/ubank.png' },
  { value: '970427', label: 'Ngân hàng TMCP Việt Á (VAB)', img: 'https://vietqr.co/storage/banks/vab.png' },
  { value: '970405', label: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (VBA)', img: 'https://vietqr.co/storage/banks/vba.png' },
  { value: '999888', label: 'Ngân hàng Chính sách Xã hội (VBSP)', img: 'https://vietqr.co/storage/banks/vbsp.png' },
  { value: '970436', label: 'Ngân hàng TMCP Ngoại Thương Việt Nam (VCB)', img: 'https://vietqr.co/storage/banks/vcb.png' },
  { value: '970454', label: 'Ngân hàng TMCP Bản Việt (VCCB)', img: 'https://vietqr.co/storage/banks/vccb.png' },
  { value: '970441', label: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)', img: 'https://vietqr.co/storage/banks/vib.png' },
  { value: '970433', label: 'Ngân hàng TMCP Việt Nam Thương Tín (VIETBANK)', img: 'https://vietqr.co/storage/banks/vietbank.png' },
  { value: '970432', label: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPB)', img: 'https://vietqr.co/storage/banks/vpb.png' },
  { value: '970421', label: 'Ngân hàng Liên doanh Việt - Nga (VRB)', img: 'https://vietqr.co/storage/banks/vrb.png' },
  { value: '970457', label: 'Ngân hàng TNHH MTV Woori Việt Nam (WVN)', img: 'https://vietqr.co/storage/banks/wvn.png' },
  { value: '977777', label: 'Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam) (MAFC)', img: 'https://vietqr.co/storage/banks/mafc.png' },
  { value: '971011', label: 'Trung tâm dịch vụ tài chính số VNPT- Chi nhánh Tổng công ty truyền thông (VNPT Fintech) (VNPTMONEY)', img: 'https://vietqr.co/storage/banks/vnptmoney.png' },
  { value: '971005', label: 'Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội (VTLMONEY)', img: 'https://vietqr.co/storage/banks/vtlmoney.png' },
  { value: 'momo', label: 'Ví điện tử MoMo (MOMO)', img: 'https://vietqr.co/storage/banks/momo.png' },
  { value: 'viettelmoney', label: 'Viettel Money - Tài khoản tiền di động (VIETTELMONEY)', img: 'https://vietqr.co/storage/banks/viettelmoney.png' },
]